version: 1.0.0-{build}
configuration: Release

environment:
  github_auth_token:
    secure: +vzVo4DsD93fPeSkrIL12KQsq2VJrge4ZSt3KanSxtnifHsBXYmGko4Ck00sVOqD
  sonar_token:
    secure: GBaeujJgXPbcDto3kyJXpwrTJdPNKNOjwzyzAGNvvKYg+X/S3anpG+8qKMBjjGFI
  myget_token:
	secure: TWVKxbiZneCbY9ckMQxFhV+jhSir05VD2ZoX9lMzfSPCbjUdLo/FUZh3hemWcgGb

build_script:
- ps: >-
	.build\build.ps1
	.build\sonar_run.ps1

artifacts:
- path: artifacts\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/nlogmongodbnetcore/api/v2/package
  api_key:
    secure: $env:myget_token
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master